### ISSUE TITLE
Token HUD missing from token

### ISSUE THREAD

**Issue by Orionox** [Aedif/TokenVariants#48] opened 2022-03-19 15:00 UTC
I don't know why but one of my players no longer has the button on the token HUD. I've check both their setting s and mine and soo nothing that should be causing the token to be missing the button. The last thing I was doing before the button went missing was clearing out some broken links that they could select from. After I had done that, the button disappeared and I can't get iot back

**Comment by Aedif** [comment] 2022-03-20 13:44
Hi,

Do you notice any errors in the console?

It would also be useful to me if you could run the following in the console and try to open the HUD for a token:

``game.settings.set("token-variants", "debug", true)``

It should give an output such as this which might help me find the problem:

![image](https://user-images.githubusercontent.com/7693704/159164564-ea9435b1-61c0-49ad-92ce-bec8360716c3.png)

Lastly what do you mean by "clearing out some broken links". Did you delete the images, right-clicked them on the Token HUD, removed them from a rolltable?

**Comment by Orionox** [comment] 2022-03-20 15:43
![Capture](https://user-images.githubusercontent.com/20059838/159170446-cdaf9293-b053-4b80-bb27-66cc58c31292.PNG)
Here's the error I was getting from the token. I ended up just remaking the token from scratch. What I mean by clearing link, was going through the variant UI clicking on the pictures to get rid of the green arrow thing for several images that got moved.

**Comment by Aedif** [comment] 2022-03-21 12:54
I was able to reproduce the issue. It should be fixed in [Release 1.28.2](https://github.com/Aedif/TokenVariants/releases/tag/1.28.2)

Caused by right-clicking the very edge of the image and the module becoming unable to find the image name and path.

If you find any more actors with a broken Token HUD button you can fix them by selecting a token and running the following:

``game.actors.get(canvas.tokens.controlled[0].data.actorId).unsetFlag('token-variants', 'variants')``

**Closed** 2022-03-22 00:07 UTC
Labels: bug
