### ISSUE TITLE
Unable to save settings of compendium mapper

### ISSUE THREAD

**Issue by uniwars** [Aedif/TokenVariants#113] opened 2023-06-05 14:51 UTC
Hi, whenever I try to save settings from the compendium mapper tool I get this error :
![image](https://github.com/Aedif/TokenVariants/assets/65986545/92e489fa-3efb-4b39-a796-2d93ac57b2e8)

Module at last version, on foundry v10 and pathfinder 2 system 4.12.9

**Comment by Aedif** [comment] 2023-06-05 15:27
Thanks for reporting, will be fixed in next release 👍

**Comment by uniwars** [comment] 2023-06-12 17:47
Hello, thanks for the fix. I can save now, but nothing seems to be saved, if I re-open the search settigns menu just after saving it it will be default and I don't think it will save neither if mapping just after saving it
I'm trying to map NPC and a "Commoner" get assigned a "Ghost commoner" image, I thought chaging the % from 70 to 90 would prevent this, so either it's not saving my change, either the change does nothing for my problem

**Comment by Aedif** [comment] 2023-06-13 07:48
Fuzzy search will match `Commoner` to `Ghost Commoner` with 100% match. You can see this by opening up an Art Select, typing in `Commoner` and hovering over the image:

![image](https://github.com/Aedif/TokenVariants/assets/7693704/7ad893f5-9c8b-40d2-b4a1-65ca6b095d8c)

This is intended behaviour. However `Commoner` wiill be prioritized by the module over `Ghost Commoner`  during `Auto Apply`

**Comment by uniwars** [comment] 2023-06-13 10:27
I'm using auto-apply and it seems to choose ghost commoner
I can't set more then 70% I think because when I sav the search settings the menu close but nothing changed when I open it again

**Comment by uniwars** [comment] 2023-07-12 23:34
Hi, I updated to v11 last stable, and token variant art last version and the search settings of the compendium mapper still doesn't save

I change things in the settings, click "save changes", the settigns window closes and then nothing has changed, so I can't use the "exact name" option for example or change the % match as each time I save and the window closes all is reset to default

**Closed** 2023-07-13 11:16 UTC
