### ISSUE TITLE
Option to disable popups when copy/pasting tokens in a scene

### ISSUE THREAD

**Issue by MrPotatoZed** [Aedif/TokenVariants#22] opened 2021-09-12 01:26 UTC
I'm not sure if this is expected behavior or not. I have the "disable automatic popups" option selected and it does prevent the popup when dragging actors onto the scene for the first time. However, I'm still getting the popup when I copy/paste actors on scene.
![variantart-copypaste1](https://user-images.githubusercontent.com/85974617/132967240-fc7f2a33-1655-4f3d-a38b-3fa52590f12c.gif)
I'm using token variant art's awesome indexing options primarily to allow image switching with the token hud button and as a tie in with tokenizer so it would be great if it were possible to disable variant art popups for both token creation and copy/pasting. Having to close several windows when copy/pasting multiple actors can get a bit cumbersome.

In case the current behavior isn't expected, I'm running v8.9, 5e 1.4.3, token variant art 1.12.1. There are no errors in console. Tested on the forge and local install. I get the same behavior with only token variant art running in a clean world.

**Comment by Aedif** [comment] 2021-09-12 09:52
This was not intended and should now be fixed in release 1.12.2

If curious this was a byproduct of the very much intended behaviour of triggering the pop-up when Ctrl/Alt/Shift are held during token creation (relevant when dragging in tokens). Since you paste while pressing Ctrl+V the Ctrl is registered as held and so the pop-up was displayed.

**Comment by MrPotatoZed** [comment] 2021-09-13 01:08
Thanks for looking into this. It is no longer giving the search popup when I cut/paste with "disable automatic popups" selected so that's working great. At this point the only time get the automatic popup is when I uncheck "disable automatic popups" and then use the create actor button in the actors directory. There is no automatic popup when an actor is dragged on to a scene or when a token is cut/pasted on a scene, even with "disable automatic popups" not selected. This works great for my use case; just want to make sure it's the expected behavior.

**Closed** 2021-09-16 03:35 UTC
Labels: bug
