### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Nedrapter** [Aedif/TokenVariants#99] opened 2023-02-23 19:26 UTC
I'm trying to find some comprehensible guide on how to use the module and what exactly it can or can't do and I'm super confused. The wiki is half red saying I lack permission to update when clicking on the red links.

What I'm trying to find out is if it's possible to:
Allow each player to switch between a selected few token images, while **not having access** to other players' images. Meaning that Player 1 using the Token HUD sees and can pick between image A, B, or C while Player 2, sees and can pick between images D, E or G. It's important that the image access is separated.
I'm also using the Forge if that matters.

**Comment by Aedif** [comment] 2023-02-23 19:47
The only way this would be possible is if your User1 had images A, B, and C in their Asset Library, and your User2 had images D, E, and G in their own.

Then each user would need to go into module settings and setup the 'Forge Assets Library Paths' to point to a folder inside their Asset Library containing these images and set the setting to NOT 'Share' it:
![image](https://user-images.githubusercontent.com/7693704/221013187-f6af159c-8f49-497d-a367-ea789882c11e.png)

What this does is expose User1 Asset Library to the module but only for themselves (as they chose not to 'Share' the path with anyone else).

Thyen when the User1 clicks on the Token HUD the module will only find the images that mathc up in their Asset Library (A, B, C).

Same applies for User2 and their Asset Library images (D, E, G)

**Comment by Nedrapter** [comment] 2023-02-24 05:23
Explaining it to my players, I also noticed they seem to have full access to all the module's settings. Is that intended?

**Comment by Aedif** [comment] 2023-02-24 06:29
They should only have access to 'Forge Assets Library Payhs' and 'Token HUD Client Settings', unless you've configured your players as GMs.

**Comment by Nedrapter** [comment] 2023-02-24 06:44
I don't have them as GM. No elevated permissions on pretty much anything. These have access to all this
![image](https://user-images.githubusercontent.com/74311190/221110531-2c100028-9730-47f2-b416-0978a9581820.png)

**Comment by Aedif** [comment] 2023-02-24 06:53
I just tested and my users only have access to the client specific settings. Make sure you haven't given this permission to your players:

![image](https://user-images.githubusercontent.com/7693704/221112182-7d7ff437-84be-4293-a746-0529a611fd3c.png)

**Comment by Nedrapter** [comment] 2023-02-24 06:57
I see. They did have that permission, as I thought it was required for general Foundry settings and modules like Dice so Nice. Apparently it's not for that. Turned it off, all good! Thanks!

**Comment by Aedif** [comment] 2023-02-24 23:24
If the problem is resolved feel free to close the issue.

Regarding the wiki, it is still incomplete. I work on it a bit whenever I have the time and the will but the big scope of the module and up until recently rapid development meant that documentation always lagged behind.

**Closed** 2023-02-24 23:24 UTC
